"""empty message

Revision ID: 0bd8ebd3394d
Revises: 2a4a7598d4ee
Create Date: 2026-01-20 18:47:24.786932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd8ebd3394d'
down_revision = '2a4a7598d4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('restaurants_owner_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_unique_constraint('restaurants_owner_id_key', ['owner_id'])

    # ### end Alembic commands ###
