"""empty message

Revision ID: 48446cefdbe3
Revises: 5f0b0cfd5509
Create Date: 2026-01-13 09:42:31.119176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48446cefdbe3'
down_revision = '5f0b0cfd5509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['order_id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
