"""empty message

Revision ID: 9ce90c87305e
Revises: 0bd8ebd3394d
Create Date: 2026-01-20 19:22:35.128901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce90c87305e'
down_revision = '0bd8ebd3394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_restaurant_id_fkey', type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('restaurants_owner_id_fkey', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('restaurants_owner_id_fkey', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_restaurant_id_fkey', 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###
